export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    SET_CART : "SET_CART",
    LOG_IN : "LOG_IN",
    LOG_OUT : "LOG_OUT"
};